Web/WebWarehouse.Web/Controllers/GoodsController.cs
using Microsoft.AspNetCore.Identity;
using WebWarehouse.Data.Models;

namespace WebWarehouse.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using WebWarehouse.Services.Data.Goods;
    using WebWarehouse.Services.Data.Measures;
    using WebWarehouse.Web.ViewModels.Common.SelectLists;
    using WebWarehouse.Web.ViewModels.Goods;

    public class GoodsController : BaseController
    {
        private readonly IGoodsService goodsService;
        private readonly IMeasuresService measuresService;
        private readonly UserManager<ApplicationUser> userManager;

        public GoodsController(
            IGoodsService goodsService,
            IMeasuresService measuresService,
            UserManager<ApplicationUser> userManager)
        {
            this.goodsService = goodsService;
            this.measuresService = measuresService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = new GoodListViewModel()
            {
                Goods = await this.goodsService.GetAllAsync<GoodViewModel>(),
            };
            return this.View(viewModel);
        }

        public async Task<IActionResult> Add()
        {
            var measures = await this.measuresService.GetAllAsync<MeasureSelectListViewModel>();
            this.ViewData["Measures"] = new SelectList(measures, "Id", "Name");

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(GoodInputModel model)
        {
            // TODO: Authentication and Authorization
            var goodId = await this.goodsService.AddAsync(model);
            return this.Redirect("All");
        }
    }
}

Web/WebWarehouse.Web/Views/Goods/Add.cshtml
@model WebWarehouse.Web.ViewModels.Goods.GoodInputModel
@{
    ViewData["Title"] = "Create a New Goods";
    var measures = this.ViewData["Measures"] as SelectList;
}

<h1>@this.ViewData["Title"]</h1>
<h3>Some text here how or why to create new goods.</h3>

<div class="col-lg-6">
    <form method="post" enctype="multipart/form-data" class="pt-4">

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">SKU</label>
            <div class="col-sm-10">
                <input type="text" asp-for="@Model.SKU" class="form-control" required="required">
                <span asp-validation-for="SKU" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Barcode</label>
            <div class="col-sm-10">
                <input type="text" asp-for="@Model.Barcode" class="form-control">
                <span asp-validation-for="Barcode" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" asp-for="@Model.Name" class="form-control" required="required">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Measure</label>
            <div class="col-sm-10">
                <select asp-for="@Model.MeasureId" class="form-control" asp-items="@measures">
                </select>
                <span asp-validation-for="MeasureId" class="text-danger"></span>

                <span>
                    <a class="btn btn-info" data-toggle="tooltip" data-placement="left" title="Tooltip on top" asp-controller="Measures" asp-action="Create">Add New Measure</a>
                </span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Delivery Price</label>
            <div class="col-sm-10">
                <input type="number" asp-for="@Model.DeliveryPrice" class="form-control" required="required">
                <span asp-validation-for="DeliveryPrice" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Sale Price</label>
            <div class="col-sm-10">
                <input type="number" asp-for="@Model.SalePrice" class="form-control" required="required">
                <span asp-validation-for="SalePrice" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Quantity</label>
            <div class="col-sm-10">
                <input type="number" asp-for="@Model.Quantity" class="form-control" required="required">
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-6 text-right">
                <button type="submit" class="btn btn-success" asp-controller="Goods" asp-action="Add">
                    Add Goods
                </button>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-danger" asp-controller="Goods" asp-action="All">Cancel</a>
            </div>
        </div>

    </form>
</div>

Web/WebWarehouse.Web/Views/Goods/All.cshtml
@using WebWarehouse.Common
@model WebWarehouse.Web.ViewModels.Goods.GoodListViewModel
@{
    ViewData["Title"] = "All";
}

<h2>
    All Goods: (@Model.Goods.Count())
    <span>
        <a class="btn btn-info" asp-controller="Goods" asp-action="Add">Add New Good</a>
    </span>
</h2>

<table class="table table-bordered table-striped">
    <thead class="thead-light">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">SKU</th>
            <th scope="col">Barcode</th>
            <th scope="col">Quantity</th>
            <th scope="col">Measure</th>
            <th scope="col">Delivery Price</th>
            <th scope="col">Sale Price</th>
            <th scope="col">Warehouse</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var good in this.Model.Goods)
        {
            <tr>
                <th scope="row">@good.Name</th>
                <td>@good.SKU</td>
                <td>@good.Barcode</td>
                <td>@good.Quantity</td>
                <td>@good.MeasureName</td>
                <td>@good.DeliveryPrice</td>
                <td>@good.SalePrice</td>
                <td>@good.WarehouseName</td>
            </tr>
        }
    </tbody>
</table>