Web/WebWarehouse.Web/Controllers/GoodsController.cs
using Microsoft.AspNetCore.Identity;
using WebWarehouse.Data.Models;

namespace WebWarehouse.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using WebWarehouse.Services.Data.Goods;
    using WebWarehouse.Services.Data.Measures;
    using WebWarehouse.Web.ViewModels.Common.SelectLists;
    using WebWarehouse.Web.ViewModels.Goods;

    public class GoodsController : BaseController
    {
        private readonly IGoodsService goodsService;
        private readonly IMeasuresService measuresService;
        private readonly UserManager<ApplicationUser> userManager;

        public GoodsController(
            IGoodsService goodsService,
            IMeasuresService measuresService,
            UserManager<ApplicationUser> userManager)
        {
            this.goodsService = goodsService;
            this.measuresService = measuresService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = new GoodListViewModel()
            {
                Goods = await this.goodsService.GetAllAsync<GoodViewModel>(),
            };
            return this.View(viewModel);
        }

        public async Task<IActionResult> Add()
        {
            var measures = await this.measuresService.GetAllAsync<MeasureSelectListViewModel>();
            this.ViewData["Measures"] = new SelectList(measures, "Id", "Name");

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(GoodInputModel model)
        {
            // TODO: Authentication and Authorization
            var goodId = await this.goodsService.AddAsync(model);
            return this.Redirect("All");
        }
    }
}

Web/WebWarehouse.Web/Controllers/PartnersController.cs
namespace WebWarehouse.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    public class PartnersController : BaseController
    {
        public async Task<IActionResult> Create()
        {
            return this.View();
        }
    }
}

Web/WebWarehouse.Web/Controllers/SalesController.cs
namespace WebWarehouse.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    public class SalesController : BaseController
    {
        public async Task<IActionResult> Create()
        {
            return this.View();
        }
    }
}

Web/WebWarehouse.Web/Controllers/TransfersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebWarehouse.Data.Models;
using WebWarehouse.Services.Data.Transfers;
using WebWarehouse.Services.Data.Warehouses;
using WebWarehouse.Web.ViewModels.Common.SelectLists;
using WebWarehouse.Web.ViewModels.Transfers;

namespace WebWarehouse.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using WebWarehouse.Services.Data.Goods;

    public class TransfersController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ITransfersService transfersService;
        private readonly IWarehousesService warehousesService;
        private readonly IGoodsService goodsService;

        public TransfersController(
            UserManager<ApplicationUser> userManager,
            ITransfersService transfersService,
            IWarehousesService warehousesService,
            IGoodsService goodsService)
        {
            this.userManager = userManager;
            this.transfersService = transfersService;
            this.warehousesService = warehousesService;
            this.goodsService = goodsService;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = new TransferListViewModel()
            {
                Transfers = await this.transfersService.GetAllAsync<TransferViewModel>(),
            };
            return this.View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var warehouses = await this.warehousesService.GetAllAsync<WarehouseSelectListViewModel>();
            this.ViewData["Warehouses"] = new SelectList(warehouses, "Id", "Name");

            var goodsList = await this.goodsService.GetAllAsync<GoodsSelectListViewModel>();
            this.ViewData["Goods"] = new SelectList(goodsList, "Quantity", "Name");

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransferInputModel model)
        {
            ;

            var userId = this.userManager.GetUserId(this.User);
            await this.transfersService.MakeTransfer(model, userId);

            return this.View();
        }
    }
}

Web/WebWarehouse.Web/Views/Shared/_Layout.cshtml
@using WebWarehouse.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap-cosmo.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/lazy.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" id="operationNavbardrop" data-toggle="dropdown">
                                Operations
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item text-break" asp-area="" asp-controller="Sales" asp-action="Create">Sale</a>
                                <a class="dropdown-item text-break" asp-area="" asp-controller="Deliveries" asp-action="Create">Delivery</a>
                                <a class="dropdown-item text-break" asp-area="" asp-controller="Transfers" asp-action="Create">Transfer</a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" id="createNavbardrop" data-toggle="dropdown">
                                Create
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item text-break" asp-area="" asp-controller="Goods" asp-action="Add">Goods</a>
                                <a class="dropdown-item text-break" asp-area="" asp-controller="Measures" asp-action="Create">Measure</a>
                                <a class="dropdown-item text-break" asp-area="" asp-controller="Partners" asp-action="Create">Partner</a>
                                <a class="dropdown-item text-break" asp-area="" asp-controller="Warehouses" asp-action="Create">Warehouse</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/lib/popper/popper.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="~/js/lazy.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>